### ISSUE TITLE
Handle large fonts with scroll thorughout onboarding screens

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#232]
# Goal
To account for large font settings in participants phones, we want to make the pages scrollable when the content overflows

## Tasks

- [x] Adjust font on login page and welcome pages to be dynamic (currently fixed to size)

- [x] Maintain current separation between the widgets (in another issue we will adapt separation between widgets to keep visual style)

- [x] Detect content overflowing and include a scrollable component to static views (no interaction or keyboard displays)

- [x] For interactive screens, the Continue button should be moved under the text input field to enable the user to continue with one tap instead of two taps

## Visual bugs that came with the scroll
   
- [x] Continue button text appears cut, but it looks fine on other pages
- [x] White background when scrolling past the top
