### ISSUE TITLE
Testing Protocol for Experiment Creation

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/Fabla-Front-end#422]
# Goal
Testing the Retool -> RDS -> Participant

## Milestones
- [ ] Create a study with general questions
- [ ] Create a participant with any study code and start date and dose date
- [ ] Create custom questions for participant
- [ ] Edit wake up time for participant
- [x] In Flutter, input the study code for the participant
- [ ] Receive correct study start date and dose date
- [ ] Receive correct amount of diaries per day
- [ ] Receive correct custom question for the participant

Living issue for filling issues and testing procedures that we should account for when making changes to the pipeline

**Comment by yago1994** [comment]
Completed
